### ISSUE TITLE
release/storage.d.ts中语法报错

### ISSUE THREAD

**Issue by zsj621** [Chechengyi/sweet-storage#17]
![image](https://user-images.githubusercontent.com/13817342/146115149-d904ada3-4adc-41d4-abd2-03cddeb756e2.png)
如图，这几个function没有返回值类型，编译时会报错。建议在后面加上任意值的返回值类型。
如：
`function save(key: Key, value: Value, time?: Time): any;`

**Comment by Chechengyi** [comment]
虽然过了很久。。 但是现在将这个问题处理了，  新的 npm 包版本：1.0.5
