### ISSUE TITLE
Hello 看了你的项目，有兴趣加入 阿里巴巴 吗？

### ISSUE THREAD

**Issue by baskinwind** [Chechengyi/sweet-storage#8]
base 在杭州，有兴趣的话可以发简历给我，zhengxuan.yzx@alibaba-inc.com
个人邮箱也可以：wwsxuan@163.com

**Comment by Chechengyi** [comment]
其实现在也在给阿里办事， 不过是阿里外包， 目前进阿里应该是没实力。 抱歉。。
